### ISSUE TITLE
video file generated by demo.py is only 15KB and cannot be played.

### ISSUE THREAD

**Issue by AndrewNest** [cfzd/Ultra-Fast-Lane-Detection#101]
Hi, thanks for sharing. I tried to visualize the results of CULane with demo.py. 
run  **python demo.py configs/culane.py --test_model model/culane_18.pth** ,but the avi video file generated by demo.py is only 15KB and cannot be played. 
The terminal didn't prompt error. There is a progress bar when running, and each video file will run for several minutes. It took 15 minutes to generate eight video files.
![QQ图片20201011203817](https://user-images.githubusercontent.com/46395243/95678848-c1272200-0c01-11eb-8adb-396815973a96.png)
this is the progress of the last avi file, it takes 3:35.

**Comment by cfzd** [comment]
@AndrewNest 
Commonly the `15kb` problem can be caused by two problems: video size mismatch and video encoder.

For the video size mismatch, please check 
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/054941161b55fa8edc92fa35fd1a515d6cf57636/demo.py#L62
and
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/054941161b55fa8edc92fa35fd1a515d6cf57636/demo.py#L91
to see if the size of `vis` is `(img_h, img_w)`.

For the video encoder, please check you have `MJPG` video encoder.
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/054941161b55fa8edc92fa35fd1a515d6cf57636/demo.py#L60

**Comment by AndrewNest** [comment]
Thank you so much for your advices. I have checked these three lines of code and there are no errors. The debug result shows that the size of (img_w, img_h) is right (1640,590), but vis={NoneType} None. So weird！
![QQ图片20201012162955](https://user-images.githubusercontent.com/46395243/95724020-6a285800-0ca8-11eb-9831-98727e6d134b.png)
![QQ图片20201012163000](https://user-images.githubusercontent.com/46395243/95724028-6bf21b80-0ca8-11eb-94c0-b0413085b222.png)

**Comment by cfzd** [comment]
@AndrewNest 
You can check here
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/054941161b55fa8edc92fa35fd1a515d6cf57636/demo.py#L84
to see if the code correctly reads the image.  If it is `None`, then the path of the image might be wrong.

**Comment by AndrewNest** [comment]
Great thanks! I have checked the path of the dataset. It turns out that I made a low-level mistake. The path contains Chinese characters. When I changed it to English characters,  the problem was solved. Thank you again for taking the time to answer me.
