### ISSUE TITLE
will RandomLROffsetLABEL cause classification ambiguity?

### ISSUE THREAD

**Issue by PJHardy** [cfzd/Ultra-Fast-Lane-Detection#117]
Thanks for your outstanding works.

I have achieved good results on my own dataset, but the performance becomes poor when changing lane(like #72 and #114).
![image](https://user-images.githubusercontent.com/31055691/97856354-1f45b180-1d37-11eb-8753-0bb46819ec03.png)
![image](https://user-images.githubusercontent.com/31055691/97856309-148b1c80-1d37-11eb-81c6-707a43c56377.png)

I was wondering if RandomLROffsetLABEL is a cause of this problem?
Assume I label 4 lanes(from left to right) as 0 1 2 3, 1 means left-ego-lane and 2 means right-ego-lane. After a offest(max to ±200 pixel),  the previous label may no longer be correct.

**Comment by cfzd** [comment]
@PJHardy 
The `RandomLROffsetLABEL` and `RandomDUOffsetLABEL` operations are used to overcome the overfitting problem. Since the pattern of the lane is relatively fixed, the model would easily overfit without these augmentations.

For the problem you said, I think it could definitely happen. But I don't know how close the problem of changing lane and these augmentations are related. 

I tried a max offset of `100`. The CULane evaluation results don't change, but I don't know how the max offset would affect the results of changing lanes.

Moreover, the rotation augmentation might also affect the performance of changing lane. When changing lane, the angle of the center lane is close to `90`, the augmentation might rotate to the **other side** (i.e. the direction of the center lane is changed and the label would wrong in this case).

The augmentations could indeed affect the results of changing lanes, but I think they are not the major reason. I think the major reason is still the ***direction-related*** labeling. Since all the annotation classes are based on direction, it could eventually result in bad performance of changing lanes, which have ambiguous directions.

**Comment by awethaileslassie** [comment]
Greetings, @PJHardy and @cfzd,

I am reopening the issue!

Thank you for raising this concern. I encountered a similar issue myself. While the network produces excellent lane detection results when the lanes are positioned on the left and right, its performance degrades significantly during lane changes. The problem lies not only in handling ambiguous lanes but also in how all lanes are adversely affected when the ego vehicle changes lanes. Having a lane detection system that fails during lane changes is not good.

Have either of you looked into the root cause and explored potential solutions? Any insights on how to address this issue would be highly appreciated.

**Comment by gebawe** [comment]
Greetings, @PJHardy and @cfzd,

I am reopening the issue!

Thank you for raising this concern. I encountered a similar issue myself. While the network produces excellent lane detection results when the lanes are positioned on the left and right, its performance degrades significantly during lane changes. The problem lies not only in handling ambiguous lanes but also in how all lanes are adversely affected when the ego vehicle changes lanes. Having a lane detection system that fails during lane changes is not good.

Have either of you looked into the root cause and explored potential solutions? Any insights on how to address this issue would be highly appreciated.
