### ISSUE TITLE
video generated  after demo.py are only of 15kb except the first video

### ISSUE THREAD

**Issue by kamalchibrani-ai** [cfzd/Ultra-Fast-Lane-Detection#122]
`python demo.py configs/culane.py --test_model culane_18.pth` 
once i execute this 
test0_normal.avi is working fine 
but rest other video generated are only of 15kb and cant play them

**Comment by cfzd** [comment]
@kamalchibrani-ai 
It's really strange since your first video is good. The problem of 15KB is usually caused by incorrect size between video and image.

Can you please check the size of `vis` in this line for other bad videos?
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/bb673eb816e5c5356dcab02d72feb937fbb445b6/demo.py#L84

**Comment by kamalchibrani-ai** [comment]
> 
> 
> @kamalchibrani-ai
> It's really strange since your first video is good. The problem of 15KB is usually caused by incorrect size between video and image.
> 
> Can you please check the size of `vis` in this line for other bad videos?
> 
> https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/bb673eb816e5c5356dcab02d72feb937fbb445b6/demo.py#L84

i didnt change the code or any file but this time it runs fine.

thanks for the early reply
