### ISSUE TITLE
关于demo

### ISSUE THREAD

**Issue by duducode** [cfzd/Ultra-Fast-Lane-Detection#128]
请问 demo 80行       loc[out_j == cfg.griding_num] = 0  的作用是什么，为什么  griding_num设为100. 当测试不同分辨率图片时，需要将图片resize到1280，720 还需要修改anchor吗

**Comment by cfzd** [comment]
@duducode 
为了处理没有车道线的情况，我们把最后一类当做"no lane"类，网络输出最后一类就意味着这一行没有车道线。
`out_j == cfg.griding_num` 就表示把所有是 "no lane"的情况取出来，就不处理了，因为没有车道线。

griding_num是参数，100,200,300都可以。表示把一行横向划分成多少个网格。

如果你resize成别的分辨率，首先可能网络的size就对不上了，因为有FC层，你要改的话就得从训练改起了。

**Comment by madasebrof** [comment]
In English:

**Q. What is the purpose of loc[out_j == cfg.griding_num] = 0 in line 80 of the demo? Why is griding_num set to 100. When testing images with different resolutions, you need to resize the images to 1280. Do you need to modify the anchor for 720?**

A. In order to deal with the situation where there is no lane line, we regard the last category as the "no lane" category. The network output of the last category means that there is no lane line in this row.

out_j == cfg.griding_num means that all the cases that are "no lane" are taken out and will not be processed because there is no lane line.

griding_num is a parameter, 100, 200, 300 are all available. Indicates how many grids a row is divided into horizontally.

If you resize to another resolution, first of all, the size of the network may not match up, because there is an FC layer, if you want to change it, you have to change it from training.
