### ISSUE TITLE
Test on the Tusimple dataset does not output test results properly, but Culane dataset does

### ISSUE THREAD

**Issue by xmoon5** [cfzd/Ultra-Fast-Lane-Detection#173]
`python test.py configs/tusimple.py --test_model  ../logs/20210219_135812_lr_4e-04_b_64/ep080.pth --test_work_dir  ./tmp/`
output: 
`merge  test_model  config`
`merge  test_work_dir  config`
`start testing...`

**Comment by cfzd** [comment]
@xmoon5 
If the program stuck, you can add `print('ckpt1')` at line 47 https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/test.py#L46-L48

Rerun the script and see if it outputs 'ckpt1'. If the code outputs 'ckpt1', it shows it reaches line 47, and the problem is in the `eval_lane` function.

**Comment by xmoon5** [comment]
yeah there is `ckpt1`
outputs:
`merge  test_model  config`
`merge  test_work_dir  config`
`start testing...`
`ckpt1`

**Comment by cfzd** [comment]
@xmoon5 
Then you can add the print check after each line in https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/60f477c7358bbe177e1117b9f229a4a4b0db0e73/evaluation/eval_wrapper.py#L153-L163.  I think this could find the stuck point.

**Comment by xmoon5** [comment]
Yeah, thanks, I have solved this problem and successfully output the test results
