### ISSUE TITLE
Overfitting 

### ISSUE THREAD

**Issue by ngocson1804** [cfzd/Ultra-Fast-Lane-Detection#184]
Your model seems to be overfit. It only works well on trained dataset. I tested it on other images and result was very bad. I dont know if my testing have any problem. Do you have same result for other images? Thank you!

**Comment by cfzd** [comment]
@ngocson1804 
I think the term **overfitting** is misused. **Overfitting** means you get high performance on the training set and low performance on the **testing set**. 

**Then, how to define a testing set?** As per your question said, can any image belong to the testing set?

Let me put it another way, how about considering another problem: Using 2000 images collected in the US to solve autonomous driving globally. Would you think this problem is realistic? If this is unrealistic, what's the reason behind this? Can we achieve good performance on these 2000 images? Then can we achieve good performance globally?

I personally recommend you to do some study on the area of [domain adaption](https://en.wikipedia.org/wiki/Domain_adaptation).
