### ISSUE TITLE
Lane changing

### ISSUE THREAD

**Issue by LoaferCH** [cfzd/Ultra-Fast-Lane-Detection#210]
Hello, I am experimenting with your model and it works really good. However, when a car changes a lane (crosses a line), model's behavior is rather disappointing. 

![photo_2021-05-12_10-24-02](https://user-images.githubusercontent.com/50664976/117935266-354ab500-b30c-11eb-8278-e4cbcfdc1657.jpg)
![photo_2021-05-12_10-24-01](https://user-images.githubusercontent.com/50664976/117935268-35e34b80-b30c-11eb-8d39-e8e8966e8654.jpg)

I understand that this is the result of lanes having their own positional numbers (2 on the left, 2 on the right).
This could be covered with extra post-processing and the middle lane could be ignored, but I wonder if this could be fixed on model level?

**Do you have any ideas on how to make the model work on such cases?** 

Once more, I really want to thank you for the great work you have done!

**Comment by cfzd** [comment]
@LoaferCH 
I'm glad to see your experiments works well.  : )

For the lane changing problem in the model level, I think it might be hard to solve this problem using a fixed sets of classifiers (corresponding to different lanes) as we do now. But I think there are other ways could work:
- Using redundant and excess classifiers to solve this. Since you could have redundant classifiers (like and empty "slot"), the middle lane could be assigned to these classifiers.
- Using hungarian matching to determine the mapping between lanes and classifiers adaptively, like [DETR ](https://arxiv.org/abs/2005.12872) does. I think this method could really work, but my several experiments failed.
- Using instance method like this [new paper](https://arxiv.org/pdf/2105.05003.pdf).

**Comment by LoaferCH** [comment]
@cfzd 
Thank you for the response!

I will read the paper and try other advises you gave. And if I manage to improve the results, I'll write here once more.
