### ISSUE TITLE
about demo.py

### ISSUE THREAD

**Issue by fornote** [cfzd/Ultra-Fast-Lane-Detection#22]
Hello, thanks for your so good works.
While I tried to visualize the results of Tusimple with demo.py, I changed the code 
`45    splits = ['test0_normal.txt', 'test1_crowd.txt', 'test2_hlight.txt', 'test3_shadow.txt', 'test4_noline.txt', 'test5_arrow.txt', 'test6_curve.txt', 'test7_cross.txt', 'test8_night.txt']` to 
`45    splits = ['test.txt']` where 'test.txt' produced by **convert_tusimple.py**.
Meanwhile, I changed the code `datasets = [LaneTestDataset(cfg.data_root,os.path.join(cfg.data_root, 'list/test_split/'+split),img_transform = img_transforms) for split in splits]` to
`datasets = [LaneTestDataset(cfg.data_root,os.path.join(cfg.data_root, split),img_transform = img_transforms) for split in splits]`.
At last, the output video test.avi whose size just 14.5kB couldn't be played.
if there is something wrong.
I want to know how to visualize the detection results of Tusimple and CULane.
thank you.

**Comment by cfzd** [comment]
@fornote 
Hi, the 14.5kB problem is a common problem in OpenCV. It is might be caused by two reasons:
- The sizes of the video and image are not consistent. The sizes in https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/65f0231dccc0070d97c6f3aa159507ad86a5488a/demo.py#L52 and https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/65f0231dccc0070d97c6f3aa159507ad86a5488a/demo.py#L81 should be the same.
- The video encoder you specified is not installed. The setting in https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/65f0231dccc0070d97c6f3aa159507ad86a5488a/demo.py#L50 should fit your video encoder.

The `demo.py` is basically written for the CULane dataset, you might need to change the above size setting to use it.

**Comment by fornote** [comment]
thank you for your reply. 
I could successfully run the demo.py to visualize the CULane dataset.
Besides, as you said and on the original modificationl, I continute to change the sizes from (1640, 590) to (1280, 720), and the output test.avi could be played successfully.
However, there is another problem that the detected lane points cannot be parallel to the road. there is a screenshot about this problem.(链接：https://pan.baidu.com/s/1NQmpb-g5RUlI74hh4XtXJw 提取码：ucds )

The following content is my subsequent modification after your reply:
from `52   vout = cv2.VideoWriter(split[:-3]+'avi', fourcc , 30.0, (1640,590))`
to      `52  vout = cv2.VideoWriter(split[:-3]+'avi', fourcc , 30.0, (1280,720))`

from `79   ppp = (int(out_j[k, i] * col_sample_w * 1640 / 800) - 1, int(590 - k * 20) - 1)`
to     `79   ppp = (int(out_j[k, i] * col_sample_w * 1280 / 800) - 1, int(720 - k * 20) - 1)`


thanks your reply again.

**Comment by cfzd** [comment]
@fornote 
It is because the predefined row-anchors for CULane and Tusimple are not the same, as you may see in `data/constant.py`. Note that the row anchors are defined in the size of `288x800`. you can the row anchors for the original image by multiplication. If the original image size is `720x1280`, then you can get the row anchors by `rows = rows * 720 / 288`.

You can fix this problem by changing the row anchors, i.e. `int(590 - k * 20) - 1)`,  to the above-mentioned row anchors of Tusimple.

**Comment by fornote** [comment]
Thank you very much. I just fixed this problem by changing`int(590 - k * 20) - 1)` to `int(720-k*4*720/288)`. If the **20** in `int(590 - k * 20) - 1)` comes from **10*590/288**. the **10** means column size of CULane which can be seen in `data/constant.py` and **4** is the corresponding size of Tusimple.
Am i understanding it right?

Thank you for your patient reply.

**Comment by cfzd** [comment]
@fornote 
Yes. It's just a simple transformation.

**Comment by gneworld** [comment]
The 10 means column size of CULane which can be seen in data/constant.py and 4 is the corresponding size of Tusimple. This " column size" should be row size, am I right?
