### ISSUE TITLE
Is it not necessary put the model path ("path_to_culane_18.pth") on speed_real.py?

### ISSUE THREAD

**Issue by ChicagoPark** [cfzd/Ultra-Fast-Lane-Detection#238]
Before asking, I am really appreciate for you to share your knowledge👍

Currently, I study this code, but I feel quite a bit strange, because how it's gonna be possible to process in real time without upload weight from speed_real.py ..?

Or is there any file should I need to execute to upload the weight before I turn on speed_real.py?

(demo.py require pth but speed_real.py is not.... I guess I miss something before do speed_real.py ...)

Thank you for checking my question.

**Comment by cfzd** [comment]
@ChicagoPark 
The reason is:  a certain network's speeds are the same, no matter what the network's weights are. Of course, you can also load the weights as the `demo.py` does. However, the speed should be the same.

You can replace this part with the parts in `demo.py`:
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/f58fcd5f58511159ebfd06e60c7e221558075703/speed_real.py#L145-L147

https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/f58fcd5f58511159ebfd06e60c7e221558075703/demo.py#L27-L39

**Comment by ChicagoPark** [comment]
holy moly I exactly understood what you are saying ! Thanks! 

So if I want to process it in real time, it is gonna be possible to make a python code similar as demo.py, isn't it?

**Comment by cfzd** [comment]
@ChicagoPark 
Yes, you can do it as demo.py.

**Comment by ChicagoPark** [comment]
Thank you for your help!!

Can I upload the result (video) on the Youtube?

I am going to mention your git hub address and your name as well !!
