### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by niushaoda** [cfzd/Ultra-Fast-Lane-Detection#3]
Excuse me，I would like to know  what  kind  of  version of cuda？and Could I test images with a CPU.Roughly how much memory is needed。

ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
 Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f1221e03950>
Traceback (most recent call last):
  File "/home/niushaoda/envs/lane-det/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 926, in __del__
    self._shutdown_workers()
  File "/home/niushaoda/envs/lane-det/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 906, in _shutdown_workers
    w.join()
  File "/home/niushaoda/envs/lane-det/lib/python3.7/multiprocessing/process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "/home/niushaoda/envs/lane-det/lib/python3.7/multiprocessing/popen_fork.py", line 48, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/niushaoda/envs/lane-det/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/niushaoda/envs/lane-det/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 3207) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.

**Comment by niushaoda** [comment]
1

**Comment by cfzd** [comment]
@niushaoda 
Hi, what's the GPU you are using? From the title, it seems that the PyTorch is not compiled with Cuda. If you install PyTorch and Cuda as
```
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch 
```
,it should install Cuda toolkit 10.1 and pytorch cuda version. You can run `conda list` to see the installed packages. If you have correctly installed, you can see `cudatoolkit 10.1.243` and `pytorch 1.5.0` with `py3.7_cuda10.1.243_cudnn7.6.3_0` build. Here's my information:
```
# Name                    Version                   Build  Channel
...
cudatoolkit               10.1.243             h6bb024c_0    defaults
...
pytorch                   1.5.0           py3.7_cuda10.1.243_cudnn7.6.3_0   pytorch
...
```

**Comment by niushaoda** [comment]
I have no gpu， Could I test images with a CPU.

**Comment by cfzd** [comment]
For the memory issue, the memory usage of our code is not large. For single GPU training with batch size as 32, the CPU memory usage is roughly 3GB and the GPU memory usage is 6511MB. For 4-GPU training with batch size as 32, the CPU memory usage is roughly 11GB and the GPU memory usage is 7035MB x 4.

You can try to decrease the batch size and use of single GPU training.

**Comment by niushaoda** [comment]
thank you.

**Comment by cfzd** [comment]
If you want to test with CPU, it is possible. You can remove the `.cuda()` call and it should be executed in CPU. Here are locations you should remove `.cuda()` call: 
[net](https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/b4f8d84cb464b11ef0cbc3e9ca45ad1594660616/test.py#L8) 
[data](https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/b4f8d84cb464b11ef0cbc3e9ca45ad1594660616/evaluation/eval_wrapper.py#L56)
Last, comment out this line: [cudnn](https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/b4f8d84cb464b11ef0cbc3e9ca45ad1594660616/test.py#L8)
The above modification is used for CULane, it is similar for Tusimple. Remove the `.cuda()` call in [here](https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/b4f8d84cb464b11ef0cbc3e9ca45ad1594660616/evaluation/eval_wrapper.py#L90).

I didn't test the above modifications, but I think it should work since the only difference between CPU inference and GPU inference is the `.cuda()` call and other settings related to this part.

**Comment by niushaoda** [comment]
ok,thank you very much, I am trying just now.
