### ISSUE TITLE
Problems about testing

### ISSUE THREAD

**Issue by littleGiao** [cfzd/Ultra-Fast-Lane-Detection#32]
When I try to test it I always get this error:

Traceback (most recent call last):
  File "demo.py", line 46, in <module>
    datasets = [LaneTestDataset(cfg.data_root,os.path.join(cfg.data_root, 'list/test_split/'+split),img_transform = img_transforms) for split in splits]
  File "demo.py", line 46, in <listcomp>
    datasets = [LaneTestDataset(cfg.data_root,os.path.join(cfg.data_root, 'list/test_split/'+split),img_transform = img_transforms) for split in splits]
  File "/home/didi/anaconda3/envs/ult/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
**TypeError: expected str, bytes or os.PathLike object, not NoneType**

No matter I use demo.py or test.py. 

This is the command I used:  python demo.py configs/tusimple.py --test_model model/tusimple_18.pth

How to solve this problem?

Thanks

**Comment by cfzd** [comment]
@littleGiao 
Because the `demo.py` is used for visualization of CULane in different scenarios. There are no splits of different scenarios on Tusimple. So just change the splits to `test.txt` in Tusimple dataset could work. Also, there might be some problem of resolution when visualizing, you can refer to [this issue](https://github.com/cfzd/Ultra-Fast-Lane-Detection/issues/22).
