### ISSUE TITLE
How to determine the number of row anchors？

### ISSUE THREAD

**Issue by Hun-ger** [cfzd/Ultra-Fast-Lane-Detection#49]
Thanks you for your contribution.
In your code,using 18 row anchors for culane dataset.
can i use more row anchors for culane dataset so that the structure loss can work well? such as 36 or more.

**Comment by cfzd** [comment]
@Hun-ger 
If you want to increase the number of row anchors, there are two things you should care about:
- modify the row anchor definition in `data/constant.py`

  The network will output the results in your newly defined row anchors.

- modify the corresponding post-processing 

  Since the output is defined with the new row anchors, the original post-processing is not compatible with it. Try to align your new output with the originally defined row anchors, because the originally defined row anchors correspond to the evaluation protocol of CULane or Tusimple dataset. 
   For example, suppose the protocol of CULane requires the network output results at lines 10, 20, 30, and 40. And your newly defined row anchors are 5, 10, 15, ..., and 40. Then you may need to discard the results at lines 5, 15, 25, and 35 to meet the requirement of the protocol.

**Comment by Hun-ger** [comment]
I  use 21 row anchors to train culane dataset. I use SGD and Adam optimizer, but the structure loss  trends are different.
When I use the SGD,relation_loss and relation_dis  decrease and then increase.When I  use Adam，they just increase. The weight are 0 of them.
Why does the same data set cause this difference？


![adam](https://user-images.githubusercontent.com/48196026/88252391-8f787c00-cce0-11ea-803a-2e2cee725711.png)
![sgd](https://user-images.githubusercontent.com/48196026/88252392-91423f80-cce0-11ea-9f0a-93ed518d54ff.png)

**Comment by cfzd** [comment]
@Hun-ger 
This phenomenon might be caused by the reasons discussed in this issue #40. As for why the two optimizers have different behaviors, I don't have the answer for now.

**Comment by Hun-ger** [comment]
thanks！
