### ISSUE TITLE
Res-34 models

### ISSUE THREAD

**Issue by SoulmateB** [cfzd/Ultra-Fast-Lane-Detection#7]
Hi, I use the models you provided and get the same results. could you provide the Res-34 models or   share the hyper-parameters when training the Res-34 models ? Because I trained the Res-34 but the results are bad. Thank you !

**Comment by cfzd** [comment]
@SoulmateB 
Hi, in general, the hyper-parameters for Res18 could also work for Res34. If you get bad results with Res34, it might be the single/multiple GPU training setting problem. 

For CULane, try to use 4-GPU training with the provided config. For Tusimple, try to use single GPU training because Tusimple is a relatively small dataset and large batch size could harm the training.

As for trained Res34 models, we would release it in the future if we have enough spare GPU time.
