### ISSUE TITLE
how to train dataset with different resolution?

### ISSUE THREAD

**Issue by jinfagang** [cfzd/Ultra-Fast-Lane-Detection#76]
The resolution is 1920x1080, slightly larget than Tusimple data, I am using tusimple configuation (raw_anchor, gird_num and cls_per_lane), the result seems totally wrong.

Doesn't it only depends on resize input resolution ? (which is 288x800)? Why changed input image got so much different result than Tusimple and cULane?

**Comment by jinfagang** [comment]
BTW, why the Tusimple raw_anchor stride is 4 and CULane is 10? For what reason to make them like this?

**Comment by cfzd** [comment]
@jinfagang 
There are two kinds of wrong results. The first one is that training does not converge at all, the prediction accuracy is poor. The second one is that training accuracy is high, but the visualization results are poor. Please clarify your situation.

It should indeed only depends on the input resolution. The stride of raw_anchor is different because it is defined by the evaluation protocol of CULane and Tusimple. 

I also updated the `data/constant.py` and `demo.py`, which might help you.

**Comment by jinfagang** [comment]
@cfzd I found that dataset number is really matters, I try to force overfit a 2500 amount images with labeld lanes. It's same label format as CULane only difference is the input resolution, but the result is really poor, hard to distinguish lane order (except the rightest lane detect is almost satisfying). but the model trained on culane works on my data, except sometimes miss detect, at least the lane is accurate and tight.

My question is. is that ok using CULane params for 1960x1080 size of images? what could be the reason in my force overfit experiment?

**Comment by cfzd** [comment]
@jinfagang 
I don't think the original size of the image could affect the results. And I don't think the number of images is a problem because Tusimple is also small.  

I'm wondering what's the order definition of your dataset. If the rightmost lane can be learned to some extent, it should be the same for other lanes. It might be the order definition or class definition of your dataset?

 For CULane, the order 1 lane, i.e., the segmentation label 1 lane is always the leftmost lane. The definition of CULane looks like this:
```
leftmost     --> id #1 and class #1 for segmentation
left         --> id #2 and class #2 for segmentation
right        --> id #3 and class #3 for segmentation
rightmost    --> id #4 and class #4 for segmentation
```

Also, I want to know is the **training** accuracies of top1, top2, and top3 very low?

**Comment by jinfagang** [comment]
@cfzd thanks, I solved my problem and now the result looks nice.

**Comment by longzeyilang** [comment]
@jinfagang would you tell me how to solve?
