### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device-side assert triggered

### ISSUE THREAD

**Issue by fanzexuan** [cfzd/Ultra-Fast-Lane-Detection#84]
I change my dataset to Tusimple format, and then run train.py, but error like this:
"RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device-side assert triggered"

please help me to fix it,  I have no idea about this,  which part I need to change?

**Comment by cfzd** [comment]
@fanzexuan 
The `device-side assert triggered` error is usually caused by an invalid class label.  For example, you have a 1000-class problem like imagenet classification problem, but the labels are `1001`, `1002` or some other numbers which are not in `[0-999]`.

**Comment by fanzexuan** [comment]
Thx very much, I think my lane labels beyond 4 lanes, I change the config/tusimple.py parameters to 10 lanes, but also appear this problems. Do you have any suggests for this problem.  Thx very much. 
I never change codes, just put  my dataset(tusimple format) as input.

**Comment by cfzd** [comment]
@fanzexuan 
You can change the `num_lanes` in the config file.

**Comment by Happy-Carrot** [comment]
I have met this problem before. I check my label to make sure them have been "one-hot" and without other value.

**Comment by fanzexuan** [comment]
I found that  my dataset is different with tusimple dataset, my dataset picture is bmp , but tusimple dataset is png, dosen't that matter, is that reason make the error ?

**Comment by cfzd** [comment]
@Happy-Carrot 
I'm wondering that the torch classification losses usually requires the label directly instead of the one-hot label, as [here](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html?highlight=crossentropyloss#torch.nn.CrossEntropyLoss) says. Why do you need to make them one-hot?

@fanzexuan 
First of all, do you still have the error?

For image formate, we use PIL as our image decoding backend, as here:
https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/054941161b55fa8edc92fa35fd1a515d6cf57636/data/dataset.py#L10-L11

I think PIL has supported BMP file, so this should not be a problem.

**Comment by Happy-Carrot** [comment]
@cfzd
My wording may be wrong.  I mean I check my label to keep all the pixels of a lane's mask in gt has the same and unique value, which is "one--hot?", probably. (〃´-ω･)  
@fanzexuan
I think the bmp format would not matter for training.
