### ISSUE TITLE
Calculation for loc, sum(prob * idx)

### ISSUE THREAD

**Issue by emtsrlee** [cfzd/Ultra-Fast-Lane-Detection#99]
Hi, Thank you for amazing work.

I'm very impressive about the computation cost and accuracy.

While I'm studying with your code, I couldn't figure it out meaning of sumation part.

`loc = np.sum(prob * idx, axis=0)`
[https://github.com/cfzd/Ultra-Fast-Lane-Detection/blob/master/demo.py#L78](url)

To my knowledge, loc(location) should be calculated by only argmax's prob * idx, not sum(prob * idx)

Could you give me any intuition for it?

Thank you in advance.

**Comment by cfzd** [comment]
@emtsrlee 


`prob` is a `num_gridding x num_row_anchors x num_lanes` tensor containing the probability of each location. The most intuitive way is to directly use `argmax` and obtain the location like this:

 ```
 loc = np.argmax(prob, axis = 0)
 ```

Then `loc` would be `num_row_anchors x num_lanes`, and it contains the location for each lane on each row anchor.
 
But we could have a better solution. Since we have the probability of each location, we can get a more precise location than directly using `argmax`.
 
Suppose we have two locations `[39,40]`, and the probability of `[39,40]` is `[0.2,0.8]`. If we use `argmax`, we would get the location of `40` since the probability of `40` is `0.8`. but we can also get a value:`39*0.2 + 40*0.8 = 39.8`, which is more precise than `argmax`. It is ***the mathematical expectation*** of locations. That's why we use it to get the location.

**Comment by emtsrlee** [comment]
Thank you for prompt reply. Now I understand it.
I might try to add some threshold there for removing very small prob
Thank you again.
